//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module AlyaVaha {
	export interface IOperationResult
	{
		Message: string;
		Success: boolean;
		Data?: string;
	}
	export interface IWindowCommand
	{
		Command: string;
		Value?: string;
	}
}
module AlyaVaha.Models {
	export interface IMaterial
	{
		Id: number;
		NazovMaterialu?: string;
		DatumVytvorenia?: any;
		DatumUpravy?: any;
		HmotnostMaterialu?: number;
		JeAktivny?: boolean;
	}
	export interface INavazovanie
	{
		Id: number;
		DatumStartu?: any;
		CasStartu?: string;
		DatumKonca?: any;
		CasKonca?: string;
		ZariadenieId?: number;
		Zariadenie?: AlyaVaha.Models.IZariadenie;
		NavazeneMnozstvo?: number;
		NavazenyPocetDavok?: number;
		PozadovaneMnozstvo?: number;
		PozadovanyPocetDavok?: number;
		VelkostDavky?: number;
		OdkialId?: number;
		Odkial?: AlyaVaha.Models.IZasobnik;
		KamId?: number;
		Kam?: AlyaVaha.Models.IZasobnik;
		MaterialId?: number;
		Material?: AlyaVaha.Models.IMaterial;
		UzivatelId?: number;
		Uzivatel?: AlyaVaha.Models.IUzivatel;
	}
	export interface IUzivatel
	{
		Id: number;
		DatumVytvorenia?: any;
		DatumUpravy?: any;
		Login?: string;
		Heslo?: string;
		Email?: string;
		JeAdmin?: boolean;
		JeAktivny?: boolean;
	}
	export interface IZariadenie
	{
		Id: number;
		NazovZariadenia?: string;
		IpAdresa?: string;
		Port?: number;
		PocetNavazeni: number;
		NavazeneMnozstvo: number;
		NavazenyPocetDavok: number;
	}
	export interface IZasobnik
	{
		Id: number;
		NazovZasobnika?: string;
		DatumVytvorenia?: any;
		DatumUpravy?: any;
		Skratka?: string;
		CestaDoVahy?: boolean;
		CestaZVahy?: boolean;
	}
}
